@extends('layouts.app')
@section('content')
    <div class="section-inner text-light">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <article style="padding: 50px 0 100px">
                        <h1>ĐIỀU KHOẢN SỬ DỤNG</h1>
                        <h2>1. Nguyên tắc</h2>
                        <p>Các điều khoản này áp dụng cho các cá nhân truy cập và sử dụng các dịch vụ được cung cấp trực tuyến tại trang web nguoila - https://nguoila.online.</p>
                        <p>Khi sử dụng website này và các dịch vụ được cung cấp, bạn hoàn toàn đồng ý rằng:</p>
                        <p>Bạn sẽ không xâm phạm, xâm nhập, tiếp cận, sử dụng hay tìm cách xâm phạm, xâm nhập, tiếp cận hoặc sử dụng bất kỳ phần nào trong máy chủ của chúng tôi, và/hoặc bất kỳ khu vực dữ liệu nào nếu không được chúng tôi cho phép;</p>
                        <p>Bạn sẽ không gửi lên hoặc truyền phát bất kỳ thông tin bất hợp pháp, lừa gạt, bôi nhọ, sỉ nhục, tục tĩu, khiêu dâm, xúc phạm, đe dọa, lăng mạ, thù hận, kích động… hoặc trái với chuẩn mực đạo đức chung của xã hội thuộc bất kỳ loại nào, bao gồm cả việc truyền bá hay khuyến khích những hành vi có thể cấu thành tội phạm hay vi phạm bất cứ điều khoản nào của luật pháp địa phương, quốc gia hay quốc tế. Chúng tôi tôn trọng quyền tự do ngôn luận, nhưng cũng bảo lưu việc có toàn quyền lược bớt, hoặc xoá bỏ một phần hoặc toàn bộ các bài viết của bạn nếu xét thấy bài viết hoặc bất kỳ thông tin gì gửi lên vi phạm những điểm nêu trên, bất kể việc vi phạm đó là rõ ràng hay chỉ là hàm ý.</p> <p>Bạn sẽ không gửi hoặc truyền bất kỳ thông điệp nào mang tính quảng cáo, mời gọi, thư dây chuyền, cơ hội đầu tư hay bất kỳ dạng liên lạc có mục đích thương mại nào mà người dùng không mong muốn, thư rác hay tin nhắn rác;</p>
                        <p>Bạn sẽ không gửi hoặc truyền bất kỳ thông tin hoặc phần mềm nào không thuộc quyền sở hữu của bạn trừ khi đó là phần mềm được cung cấp miễn phí, khkông gửi bất kỳ thông tin hay phần mềm nào có chứa bất kỳ loại virus, Trojan, bọ hay các thành phần nguy hại nào;</p>
                        <p>Bạn sẽ không gửi, xuất bản, truyền, tái sản xuất, phân phát hoặc khai thác bằng bất cứ hình thức nào với bất cứ thông tin nào thu được từ đây vào mục đích thương mại; hoặc tải lên, gửi, xuất bản, truyền, tái sản xuất hoặc phân phối dưới bất cứ hình thức nào những nội dung được bảo vệ bởi luật bản quyền và luật sở hữu trí tuệ; hoặc tạo ra các biến thể của các nội dung đó mà không có sự đồng ý bằng văn bản của chủ nhân hoặc người giữ bản quyền.</p>
                        <p>Bạn cam kết đảm bảo sử dụng hợp pháp nội dung (bao gồm nhưng không giới hạn các thông tin, dữ liệu…) đưa lên đăng tải trên website Nguoila.online.</p>
                        <h2>2. Cấm truy cập</h2>
                        <p>Chúng tôi có toàn quyền, vào mọi lúc, cấm hoặc từ chối truy cập của bạn vào website ngay lập tức và không cần báo trước nếu chúng tôi cho rằng bạn đã vi phạm bất cứ điều khoản nào trong bản Quy định này, hoặc việc cấm truy cập xuất phát từ nhận định của chúng tôi, khi chúng tôi cho rằng từ chối đó phù hợp và cần thiết trong thẩm quyền của chúng tôi.</p>
                        <h2>3. Quyền sở hữu trí tuệ và các quyền khác</h2>
                        <p>Tại các khu vực được phép đăng tải nhận xét, bạn có thể chia sẻ thông tin được phép dưới các định dạng chúng tôi mặc định và bạn phải tự chịu trách nhiệm đối với các nội dung, thông tin, hình ảnh và bất kỳ sự chia sẻ nào khác của bạn với cá nhân người sử dụng hoặc nhóm người sử dụng. Tuy nhiên, trong mọi trường hợp, chúng tôi vẫn được bảo lưu quyền xử lý các thông tin đăng tải cho phù hợp với thuần phong mỹ tục, các quy tắc đạo đức và các quy tắc đảm bảo an ninh quốc gia, và chúng tôi có toàn quyền cho phép hoặc không cho phép bài viết của bạn xuất hiện hay tồn tại trên diễn đàn hoặc tại các khu vực được phép chia sẻ thông tin.</p>
                        <p>Bạn đồng ý để chúng tôi tự do sử dụng, tiết lộ, áp dụng và sửa đổi bất kỳ ý tưởng, khái niệm, cách thức, đề xuất, gợi ý, bình luận hoặc hình thức thông báo nào khác mà bạn cung cấp cho chúng tôi một cách hoàn toàn miễn phí. Bạn từ bỏ và đồng ý từ bỏ bất kỳ quyền và yêu cầu với bất kỳ khoản tiền thưởng, phí, nhuận bút, lệ phí và/ hoặc các kiểu chi trả khác liên quan đến việc chúng tôi sử dụng, tiết lộ, áp dụng, và/hoặc chỉnh sửa bất kỳ hoặc tất cả Nhận xét của bạn.</p>
                        <h2>4. Cung cấp Nội dung cho Nguoila.online</h2>
                        <p>Bạn đồng ý trao cho chúng tôi toàn bộ quyền và cấp phép (bao gồm cả các quyền về tinh thần hay các quyền cần thiết khác) để sử dụng, trưng bày, tái sản xuất, chỉnh sửa, làm cho phù hợp, xuất bản, cung cấp, xúc tiến, dịch và tạo ra các phiên bản phái sinh hoặc tổ hợp khác, một phần hoặc toàn bộ, trên phạm vi toàn cầu mà không đòi hỏi thù lao. Sự cấp phép này được áp dụng với bất cứ dạng thức, phương tiện, công nghệ nào đã được biết đến hoặc phát triển sau này; bạn cần lưu ý rằng, các nhận xét, lời bình tại các khu vực được phép có thể tiếp tục nằm trên website của chúng tôi ngay cả khi tài khoản của bạn đã bị xóa vì bất kỳ lý do gì.</p>
                        <p>Bạn thừa nhận và đồng ý rằng chúng tôi sẽ có quyền (nhưng không có nghĩa vụ), từ chối xuất bản hoặc loại bỏ, hoặc ngăn truy cập tới bất kỳ Nội dung nào bạn cung cấp vào bất cứ lúc nào, với bất cứ lý do nào, có hoặc không có thông báo.</p>
                        <h2>5. Thông tin của bên thứ ba</h2>
                        <p>Thông tin được cung cấp tại Nguoila.online có thể chứa thông tin từ bên thứ ba hoặc được Nguoila.online chọn lọc từ các nguồn khác. Thông tin trên website Nguoila.online không được coi là khuyến nghị sử dụng, tiêu dùng, đầu tư v.v…, hoặc xác thực của Nguoila.online về bất cứ một vấn đề, biến cố hoặc sự kiện nào và với bất kỳ mục đích nào, tương ứng với bất kỳ người, sản phẩm hoặc dịch vụ nào.</p>
                        <p>Nguoila.online không chịu trách nhiệm nếu thông tin không được cập nhật theo mong muốn của bạn. website Nguoila.online không phải là đơn vị độc lập thẩm định thông tin và sẽ không khuyến cáo bất kỳ một xu hướng tiêu dùng hoặc đầu tư nào. Theo đó, chúng tôi không chấp nhận bất cứ trách nhiệm nào về các thông tin mà chúng tôi đăng tải, bạn sẽ sử dụng hoặc đặt niềm tin vào những thông tin đó với hiểu biết, trách nhiệm và nguy cơ của riêng bạn.</p>
                        <h2>6. Liên kết đến và đi từ Nguoila.online</h2>
                        <p>Các liên kết tại Nguoila.online có thể dẫn bạn tới các website khác, và bạn thừa nhận và đồng ý rằng Nguoila.online không chịu trách nhiệm về sự chính xác hoặc giá trị của bất kỳ thông tin nào do các website liên kết cung cấp.</p>
                        <p>Liên kết tới các website khác không cấu thành sự xác nhận của Nguoila.online về thông tin, sản phẩm, quảng cáo hoặc các tài liệu khác tại những website đó.</p>
                        <h2>7. Giới hạn trách nhiệm pháp lý và bảo đảm</h2>
                        <p>Tất cả thông tin chỉ dành cho việc tham khảo tổng quát của bạn. Nguoila.online không nhận bất cứ trách nhiệm nào về những thông tin đó.</p>
                        <p>Việc truy cập và sử dụng website do bạn hoàn toàn tự chịu trách nhiệm và được cung cấp NHƯ HIỆN CÓ. Nguoila.online chỉ dành cho mục đích sử dụng cá nhân và chúng tôi không đại diện cho hoặc bảo đảm về bất cứ điều gì, được phát ngôn cụ thể hay hàm ý, bao gồm cả nhưng không chỉ giới hạn trong bất kỳ bảo đảm nào về khả năng thương mại hoặc sự thích hợp cho bất cứ mục đích cụ thể nào.</p>
                        <p>Toàn bộ trách nhiệm pháp lý của chúng tôi nằm trong dịch vụ của Nguoila.online và bị giới hạn bởi pháp luật. Chúng tôi không chứng thực, bảo đảm hoặc bảo hành cho bất cứ vật liệu, sản phẩm hoặc dịch vụ nào được đưa ra thông qua chúng tôi hoặc website của chúng tôi. Chúng tôi không phải là một thành phần tham gia vào bất kỳ giao dịch nào giữa bạn và một bên thứ ba.</p>
                        <p>Trong bất kỳ trường hợp nào, Nguoila.online cũng không chịu trách nhiệm pháp lý về bạn hoặc bất kỳ người nào cho bất kỳ tổn thất nào, dù là trực tiếp, gián tiếp, bất ngờ, đặc biệt hoặc là hậu quả của sự kiện khác, kể cả thiệt hại trong kinh doanh hoặc lợi nhuận, phát sinh từ việc sử dụng hoặc không thể sử dụng thông tin của Nguoila.online, ngay cả khi Nguoila.online đã được khuyến cáo về khả năng xảy ra các tổn thất đó.</p>
                        <p>Bạn hành xử và tin tưởng hoàn toàn vào kỹ năng và khả năng đánh giá của chính bạn đối với việc sử dụng và cách hiểu đối với thông tin bạn lấy được tại Nguoila.online. Bạn chịu trách nhiệm đảm bảo rằng việc sử dụng thông tin của bạn tuân thủ tất cả các yêu cầu của pháp luật hiện hành.</p>
                        <p>Giới hạn nghĩa vụ pháp lý trong Quy định sẽ được áp dụng với quy mô đầy đủ nhất được pháp luật hiện hành cho phép.</p>
                        <h2>8. Từ chối bảo đảm</h2>
                        <p>Bạn hiểu và đồng ý rằng việc bạn sử dụng Nguoila.online và bất cứ dịch vụ hoặc nội dung nào được cung cấp trong đó (sau đây gọi chung là "Dịch vụ") đều thuộc phạm trù rủi ro riêng của bạn. Các dịch vụ được cung cấp cho bạn "như đang có" và chúng tôi từ chối mọi bảo đảm thuộc bất kỳ dạng nào, được hàm ý hoặc công bố, bao gồm nhưng không chỉ giới hạn trong các bảo hành về khả năng bán sản phẩm, sự phù hợp với một mục đích cụ thể nào đó, và sự không vi phạm.</p>
                        <p>Chúng tôi không bảo đảm, dù hàm ý hay công bố, rằng mỗi phần của dịch vụ không bị gián đoạn, không có lỗi, không có virus, đúng giờ, an toàn, chính xác, ổn định hay bất kỳ nội dung nào là an toàn cho bạn. Bạn hiểu và đồng ý rằng cả chúng tôi và những bên tham gia cung cấp dịch vụ đều không cung cấp những tư vấn chuyên nghiệp thuộc bất kỳ dạng nào và việc sử dụng những lời tư vấn đó hoặc bất kỳ thông tin nào khác đều thuộc vào quyết định riêng của bạn, với tất cả các yếu tố rủi ro của nó và không thuộc trách nhiệm của chúng tôi.</p>
                        <h2>9. Luật áp dụng</h2>
                        <p>Bạn đồng ý rằng bản Quy định sử dụng và bất kỳ bất đồng nào phát sinh từ việc bạn sử dụng website này hoặc các sản phẩm và dịch vụ của chúng tôi sẽ được giải quyết theo luật pháp hiện hành của Nước Cộng hoà Xã hội Chủ nghĩa Việt Nam. Thông qua việc đăng ký hoặc sử dụng website và dịch vụ của chúng tôi, bạn mặc nhiên đồng ý và tuân thủ toàn bộ các quy định của Luật pháp Việt Nam.</p>
                    </article>
                </div>
            </div>
        </div>
    </div>
@endsection
